// src/lib/pdfExport.js
// Client-side PDF export for OmniSensus reports (matches OmniSensusOne.html)
import jsPDF from 'jspdf';

export function exportReportPdf({
  profile = {},
  report = {},
  recommendations = '',
  onComplete = () => {},
}) {
  // PIXEL-PERFECT MATCH TO OmniSensusOne.html
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const teal = [16, 132, 126];
  doc.setFillColor(...teal);
  doc.rect(0, 0, 210, 28, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18); doc.setTextColor(255, 255, 255);
  doc.text('OmniSensus Medical', 15, 13);
  doc.setFontSize(9); doc.setFont('helvetica', 'normal');
  doc.text('AI-Powered Clinical Diagnostic Report', 15, 20);
  doc.setTextColor(200, 240, 239);
  doc.text(`Report ID: ${report.accession_number || report.report_id || '—'}  |  Date: ${
    (report.generated_at || report.visit_date ? new Date(report.generated_at || report.visit_date).toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' }) : '—')
  }`, 210 - 15, 13, { align: 'right' });
  doc.text(`Patient: ${profile.full_name || '—'}  |  Score: ${(report.health_score ?? '—')}/100`, 210 - 15, 20, { align: 'right' });

  doc.setTextColor(...teal); doc.setFont('helvetica', 'bold'); doc.setFontSize(11);
  doc.text('RISK STRATIFICATION SUMMARY', 15, 38);
  doc.setDrawColor(...teal); doc.setLineWidth(.5); doc.line(15, 40, 195, 40);

  doc.setFont('helvetica', 'normal'); doc.setFontSize(9); doc.setTextColor(80, 80, 80);
  const rows = [
    ['Composite Health Score', (report.health_score ?? '—') + '/100'],
    ['Cardiovascular Hemodynamics', (report.cardiovascular ?? '—') + '% — ' + ((report.cardiovascular ?? 0) > 50 ? 'High' : (report.cardiovascular ?? 0) > 25 ? 'Borderline' : 'Low')],
    ['Metabolic Pathogenesis', (report.metabolic ?? '—') + '% — ' + ((report.metabolic ?? 0) > 50 ? 'High' : (report.metabolic ?? 0) > 25 ? 'Borderline' : 'Low')],
    ['Renal Filtration Index', (report.renal ?? '—') + '% — ' + ((report.renal ?? 0) > 50 ? 'High' : (report.renal ?? 0) > 25 ? 'Borderline' : 'Low')],
    ['Overall Risk Classification', (report.health_score ?? 0) >= 70 ? 'LOW RISK' : (report.health_score ?? 0) >= 50 ? 'BORDERLINE RISK' : 'ELEVATED RISK'],
  ];
  let y = 50;
  rows.forEach(([k, v]) => {
    doc.setFont('helvetica', 'bold'); doc.setTextColor(40,40,40);
    doc.text(k, 15, y);
    doc.setFont('helvetica', 'normal'); doc.setTextColor(80,80,80);
    doc.text(v, 120, y);
    doc.setDrawColor(230,234,240); doc.line(15, y + 3, 195, y + 3);
    y += 10;
  });

  doc.setTextColor(...teal); doc.setFont('helvetica', 'bold'); doc.setFontSize(11);
  doc.text('VITAL SIGNS', 15, y + 8); y += 8;
  doc.setDrawColor(...teal); doc.line(15, y + 2, 195, y + 2); y += 8;
  [
    ['Heart Rate', (report.hr ?? '—') + ' bpm', '60–100 bpm'],
    ['Systolic BP', (report.bp_sys ?? '—') + ' mmHg', '90–120 mmHg'],
    ['Diastolic BP', (report.bp_dia ?? '—') + ' mmHg', '60–80 mmHg'],
    ['SpO2', (report.spo2 ?? '—') + '%', '≥95%'],
    ['Temperature', (report.temp ?? '—') + '°C', '36.1–37.2°C'],
  ].forEach(([k, v, r]) => {
    doc.setFont('helvetica', 'bold'); doc.setFontSize(9); doc.setTextColor(40,40,40); doc.text(k, 15, y);
    doc.setFont('helvetica', 'normal'); doc.setTextColor(80,80,80); doc.text(v, 100, y); doc.text(r, 155, y);
    doc.setDrawColor(230,234,240); doc.line(15, y + 3, 195, y + 3); y += 10;
  });

  doc.setFontSize(8); doc.setTextColor(150,150,150); doc.setFont('helvetica', 'italic');
  doc.text('This report is generated by the OmniSensus AI engine for clinical decision support only. It does not constitute medical advice.', 105, 285, { align: 'center' });
  doc.setDrawColor(...teal); doc.line(15, 280, 195, 280);

  doc.save(`OmniSensus-Report-${report.accession_number || '2026'}.pdf`);
  onComplete();
}
